language: ruby
bundler_args: --without system_tests development
before_install: rm Gemfile.lock || true
sudo: false
install: bundle install
script: "bundle exec rake test && jekyll build -t"
rvm:
- 2.1
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
